/**
 * @file
 * @brief FST jQuery/Ajax Library
 *
 * A JavaScript library providing support for integrating jQuery with the
 * FST Application Framework. This module includes support for Ajax calls to
 * the framework, dynamically updating content within framework templates,
 * and Ajax-based form processing.
 */

// FST Application Framework, Version 6.0
// Copyright (c) 2004-25, Norman Lippincott Jr, Saylorsburg PA USA
// All Rights Reserved
//
// The FST Application Framework, and its associated libraries, may
// be used only with the expressed permission of the copyright holder.
// Usage without permission is strictly prohibited.

var fst = new Object();

/**
 * @brief FST Actions Object
 * @var Object fst.action;
 *
 * FST actions are triggered by hyperlinks that begin with '?'. The default
 * behavior of such a hyperlink is to initiate an Ajax request (options for
 * which may be specified via the fst_DOT_ajax_DOT_options function).
 * However, if a function
 * exists in the fst_DOT_action object corresponding to the action name, that
 * function is invoked instead. For example,
 * if fst.action.foo is a function,
 * the the hyperlink with href '?foo' will trigger this function rather than
 * invoking an Ajax request.
 * In addition, button elements generated by the framework with actions
 * beginning with '?' will exhibit the same behavior.
 */
fst.action = new Object();

/**
 * @brief Send Ajax request to the framework.
 * @fn undefined fst.ajax (String action, Object options);
 * @param action Name of action handler, optional
 * @param options Key/value pairs to define options
 *
 * Sends an Ajax request to the framework, which calls the controller's Ajax
 * handler for the named action. The response from the controller's Ajax
 * handler is passed to the callback function, if one is supplied.
 */
fst.ajax = function (action, options) {

	// Create URL for Ajax request by adding a '?' to the front of action.
	var url = '?' + action;

	// Remove any parameters from the action. For example, if the action
	//	passed was 'foo&bar=none', the action will be converted to 'foo'.
	action = action.replace(/\W.*$/, '');

	// Apply default options for those not supplied; valid options are:
	//	callback - Callback function, controller responsed passed
	//	data - Data to be passed to controller, via POST
	//	preprocess - Pre-processing function, called before Ajax call
	//	postprocess - Post-processing function, called after Ajax call
	options = jQuery.extend(
		new Object(),
		fst.ajax._options._default,
		(fst.ajax._options[action] === undefined ?
			new Object() : fst.ajax._options[action]),
		(options === undefined ? new Object() : options)
	);

	// Pre-processor function receives the options object (with defaults
	//	applied) as parameters (and could thus modify the options). If the
	//	preprocessor returns false, do not proceed with ajax call.
	if (options.preprocess(options) === false)
		return false;

	// If the confirm option is provided, display a confirmation message
	//	prior to initiating the Ajax request. If the FST jQueryUI module
	//	is installed, fst.dialog.confirm is used for the confirmation
	//	question. Otherwise, the standard JavaScript confirm function is
	//	used. (Note that the preprocess function, which receives the options
	//	as a parameter, may modify the confirm option in order to customize
	//	the confirm message (or disable it) depending on context.)
	if (options.confirm !== false) {
		if (fst.dialog && fst.dialog.confirm) {
			fst.dialog.confirm(options.confirm, {
				ok: options.confirm_ok,
				cancel: options.confirm_cancel,
				callback: function (confirmed) {
					if (confirmed) {
						options.preprocess_confirmed(options);
						options.preprocess = function () { };
						options.confirm = false;
						fst.ajax(action, options);
					}
					else {
						options.preprocess_denied(options);
						options.postprocess();
					}
				}
			});
			return false;
		}
		else {
			if (confirm(options.confirm))
				options.preprocess_confirmed(options);
			else {
				options.preprocess_denied(options);
				options.postprocess();
				return false;
			}
		}
	}

	// Send request to controller via Ajax. Upon completion, the callback
	//	function is called with the controller response as a parameter, then
	//	the postprocess function is called (with no parameters).
	jQuery.ajax( { url: url, data: options.data, type: 'POST' } )
		.done(function (response) {
			// Callback function receives the action and the response from
			//	the controller as parameters
			options.callback(response);
			// Post-processing function receives the action as a parameter
			options.postprocess();
		});

	return false;
};

fst.ajax._options = new Array();
fst.ajax._options._default = {
	callback: function (response) { },
	confirm: false,
	confirm_ok: 'OK',
	confirm_cancel: 'Cancel',
	data: new Object(),
	preprocess: function (options) { },
	preprocess_confirmed: function (options) { },
	preprocess_denied: function (options) { },
	postprocess: function () { }
};

/**
 * @brief Register options for Ajax action.
 * @fn undefined fst.ajax.options (String action, Object options);
 * @param action Ajax action (which gets sent to FST controller)
 * @param options Ajax options
 *
 * For a given Ajax action, sets the default option to be used when that
 * action is initiated.
 */
fst.ajax.options =
	function (action, options) { fst.ajax._options[action] = options; }

/**
 * @brief Register default Ajax options.
 * @fn undefined fst.ajax.options_default (Object options);
 * @param options Default Ajax options
 *
 * Registers the default options for all Ajax actions. These defaults will be
 * overridden by options defined using fst_DOT_ajax_DOT_options, then will be
 * subsequently overridden by options provided when calling fst_DOT_ajax.
 */
fst.ajax.options_default = function (options)
	{ jQuery.extend(fst.ajax._options._default, options); }

/**
 * @brief Update framework content section via Ajax.
 * @fn undefined fst.content (String name, Object options);
 * @param name Name of content area (specified in controller template)
 * @param options Data to be passed via Ajax, optional
 *
 * Sends an Ajax request to the framework, which produces HTML content to
 * replace a content area in the page. The content area is (usually) a DIV
 * that was generated when the framework was initially producing the page.
 */
fst.content = function (name, options) {

	// Apply default options for those not supplied; valid options are:
	//	data - Data to be passed to controller, via POST
	//	preprocess - Pre-processing function, called before Ajax call
	//	postprocess = Post-processing function, called after Ajax call
	options = jQuery.extend({
			data: new Object(),
			preprocess: function () { },
			postprocess: function () { }
		},
		options === undefined ? new Object() : options);

	options.data._content = name;

	// Pre-processor function receives the options (with defaults applied)
	//	as a parameters (and could thus modify the options). The is applied
	//	to the element being updated (and can be accessed as 'this').
	//	being updated is *this*.
	options.preprocess.apply(fst.content.element(name), [ options ]);

	// Send Ajax request to controller to get content. Update content
	//	element with response from controller, then call postprocess
	//	function (applied to element being updated).
	jQuery.ajax({
		url: '?_content',
		data: options.data,
		type: 'POST',
	}).done(function (response) {
		fst.content.element(name).html(response);
		options.postprocess.apply(fst.content.element(name));
		// Call all registered ready functions, if any
		jQuery.each(fst.content._ready, function (idx, fcn) {
			fcn(fst.content.element(name));
		});
	});
};

/**
 * @brief Get FST content element by name.
 * @fn Object fst.content.element (String name);
 * @param name Name of the FST content area (optional)
 *
 * Returns a jQuery object for the HTML element of the named content area.
 * If name is not given, returns the HTML element of the main content area.
 */
fst.content.element = function (name) {
	return jQuery(
		'[data-fst="content' + (name === undefined ? '' : '-' + name) + '"]');
}

/**
 * @brief Register ready function for framework content update
 * @fn undefined fst.content.ready (function fcn);
 * @param fcn Ready function
 *
 * Registers a ready function for framework content updates. When framework
 * content is updated via the fst_DOT_content function, all registered ready
 * functions are called after the content update is complete. The ready
 * functions receive the updated content element as a parameter.
 */
fst.content.ready = function (fcn) { fst.content._ready.push(fcn); }
fst.content._ready = new Array();

fst.form = new Object();
fst.form._options = new Array();

/**
 * @brief Default form cancel action
 * @fn undefined fst.form.cancel ();
 *
 * A function that defines the default action taken when the user clicks the
 * cancel button on an FST-generated form. The default behavior is to redirect
 * to the previous page (except for forms within jQueryUI dialogs, in which
 * case the dialog is closed). To change the behavor for a single form,
 * specify the cancel option by using fst_DOT_form_DOT_options. To change
 * the default behavior, re-define this function by assigning a new function
 * to fst_DOT_form_DOT_cancel.
 */
fst.form.cancel = function () { fst.redirect.back(); }

/**
 * @brief Get form data as an object.
 * @fn Object fst.form.data (Object form);
 * @param form Form object (or selector for form object)
 * @return An object containing all form data
 *
 * Returns an object with a named member for each form data item.
 */
fst.form.data = function (form) {
	var data = new Object();
	jQuery(form).find('select[multiple]').each(function () {
		data[jQuery(this).prop('name')] = jQuery(this).val();
	});
	jQuery(form).find('div[data-fst="form-control-multiple"]')
			.each(function () {
		var name = jQuery(this).attr('data-fst-name');
		data[name] = new Array();
		$(this).find('input[data-fst="form-control-multiple-option"]:checked')
				.each(function () {
			data[name].push($(this).val());
		});
	});
	jQuery.each(jQuery(form).serializeArray(), function (_, kv) {
			if (!data[kv.name])
				data[kv.name] = kv.value;
		});
	return data;
}

/**
 * @brief Convert FST date control to jQuery datepicker.
 * @fn undefined fst.form.datepicker (mixed ctl);
 * @param ctl Form(s), control(s), selector, or undefined
 *
 * Converts given FST date controls to jQuery datepicker, if installed. If
 * ctl is not given, all FST date controls are converted to use the jQuery
 * datepicker. If ctl is a Form object, all fst date controls in the given
 * form are converted. Otherwise, all FST date controls in the matched set
 * are converted.
 */
fst.form.datepicker = function (ctl) {

	// Determine if jQueryUI datepicker is installed
	if (fst._init._datepicker_installed === undefined)
		fst._init._datepicker_installed = jQuery().datepicker !== undefined;
	if (!fst._init._datepicker_installed)
		return;

	// If ctl undefined, consider all FST date controls
	if (ctl === undefined) {
		fst.form.datepicker($('[data-fst="form-control-date"]'));
		return;
	}

	// Convert each FST date control, if jQueryUI datepick is installed
	jQuery(ctl).filter('[data-fst="form-control-date"]').each(function () {
		jQuery(this).attr('type', 'text');
		jQuery(this).blur();
		if (jQuery(this).val())
			jQuery(this).val(fst.dt_mdy(jQuery(this).val()));
		var options = { };
		if (jQuery(this).attr('max'))
			options.maxDate = fst.dt_mdy(jQuery(this).attr('max'));
		if (jQuery(this).attr('min'))
			options.minDate = fst.dt_mdy(jQuery(this).attr('min'));
		jQuery(this).datepicker(options);
		jQuery(this).data('fst', 'form-control-datepicker');
	});
}

/**
 * @brief Set form field error message.
 * @fn undefined fst.form.error (Object form, String fld, String msg, boolean clear);
 * @param form Form object (or selector for form object)
 * @param fld Field name
 * @param msg Error message
 * @param clear Clear previous error messages (default false)
 *
 * Sets the error message string for the given field with an FST-generated
 * form.
 */
fst.form.error = function (form, fld, msg, clear) {
	var err = jQuery('#' + jQuery(form).attr('id') + '_' + fld)
		.parents('[data-fst="form-controls-row"]')
		.siblings('[data-fst="form-error"]');
	err.html(clear ?
		'<div>' + msg + '</div>' : err.html() + '<div>' + msg + '</div>');
}

/**
 * @brief Set form error messages.
 * @fn undefined fst.form.errors (Object form, Object errors);
 * @param form Form object (or selector for form object)
 * @param errors Name/value pairs of field names and error messages
 *
 * Sets error message strings for the field names given. The errors object
 * contains name/value pairs of field names and their corresponging error
 * messages.
 * This function is used as the default callback for Ajax form
 * submissions that fail validation.
 */
fst.form.errors = function (form, errors) {
	var form_id = jQuery(form).attr('id');
	jQuery.each(errors, function (fld, msg) {
		fst.form.error(form, fld, msg);
	});
}

/**
 * @brief Clear form error messages.
 * @fn undefined fst.form.errors.clear (Object form);
 * @param form Form object (or selector for form object)
 *
 * Clears all error messages in the given form. This is used as the default
 * preprocessor function for Ajax form submission.
 */
fst.form.errors.clear = function (form)
	{ jQuery(form).find('[data-fst="form-error"]').html(""); }

/**
 * @brief Get controller form name.
 * @fn String fst.form.name (mixed form);
 * @param form Form selector or form object
 * @return Controller form name (string), or false if not available
 *
 * Given a form selector or a form object, returns the name of the form as
 * recognized by the FST controller.
 */
fst.form.name = function (form) {
	var action = jQuery(form).attr('action');
	return jQuery(form).attr('data-fst') == 'form' &&
			/^\?_form=\w+$/.test(action) ?
		action.substring(7) : false;
}

/**
 * @brief Set default options for a given form.
 * @fn undefined fst.form.options (mixed name, Object options);
 * @param name Controller form name, form selector, or form object
 * @param options Name/value pairs of form option
 *
 * Sets the default options for forms submitted via Ajax to the FST
 * controller. Form options are associated with the controller's form name,
 * not individual form objects or form id's. If the name parameter passed does
 * not match word characters (by regular expression), it is assumed to be a
 * form object or form selector, in which case the name will be derived from
 * it.
 */
fst.form.options = function (name, options) {
	var ctlname = (jQuery.type(name) == 'string' && /^\w+$/.test(name)) ?
		name : fst.form.name(name);
	fst.form._options[ctlname] = options;
}

/**
 * @brief Sets initialization options.
 * @fn undefined fst.init (Object options);
 * @param options Initialization options
 *
 * Sets FST initialization options. This is to be called during page load and
 * affects how date/time form inputs may be altered after the page is loaded,
 * and after dialogs (if fst-jqueryui is used) are opened.
 *
 * Initialization options are as follows:
 *	datepicker - May be true, false, or 'legacy'. If true and jQueryUI
 *		datepicker is installed, date inputs are converted to use the jQueryUI
 *		datepicker. If 'legacy', converts only if the browser has no native
 *		support for date controls. If false, no conversion of date controls.
 *		Default: false.
 *	timeselect - May be true, false, or 'legacy'. If true, converts time
 *		controls to selection controls. If 'legacy', converts only if the
 *		browser has no native support for time controls. If false, no
 *		conversion for time controls. Default: false.
 */
fst.init = function (options) { jQuery.extend(fst._init, options); }
fst._init = { datepicker: false, timeselect: false }

/**
 * @brief Redirects to the given location.
 * @fn undefined fst.redirect (String uri);
 * @param uri Relative or absolute URI
 *
 * Redirect the browser to the given location. The location may be absolute,
 * in which case it is used as-is, or relative, in which case it is to be
 * given relative to the application root (thus it corresponds to the FST
 * controller arguments).
 */
fst.redirect = function (uri) { window.location = fst.uri(uri); }

/**
 * @brief Redirects to the application home page.
 * @fn undefined fst.redirect.home ();
 */
fst.redirect.home = function () { fst.redirect(''); }

/**
 * @brief Redirect to a browser history location.
 * @fn undefined fst.redirect.back (int n);
 * @param n Number of pages to go back (default is 1)
 *
 * Redirect the browser to some number of pages in the browser history. If the
 * number of pages is not given, redirects to the previous page.
 */
fst.redirect.back = function (n)
	{ n ? window.history.go(-n) : window.history.back(); }

/**
 * @brief Reload the current page.
 * @fn undefined fst.reload ();
 *
 * This is a convenience function which remains consistent with other related
 * FST jQuery functions.
 */
fst.reload = function () { window.location.reload(); }

/**
 * @brief Replaces window location in history.
 * @fn undefined fst.replace (String uri);
 * @param uri Relative or absolute URI
 *
 * Redirects the browser window while replacing the current page in the
 * browser history.
 * The URI behavior is the same as that of fst_DOT_redirect.
 */
fst.replace = function (uri) { window.location.replace(fst.uri(uri)); }

/**
 * @brief Replaces window location with the application home page.
 * @fn undefined fst.replace.home ();
 */
fst.replace.home = function () { fst.replace(''); }

/**
 * @brief Convert FST time control to selection timeselect.
 * @fn undefined fst.form.timeselect (mixed ctl);
 * @param ctl Form(s), control(s), selector, or undefined
 *
 * Converts given FST time controls to selection controls. If ctl is not
 * given, all FST time controls are converted to use selection controls.
 * If ctl is a Form object, all fst time controls in the given form are
 * converted. Otherwise, all FST time controls in the matched set are
 * converted.
 */
fst.form.timeselect = function (ctl) {

	// If ctl undefined, consider all FST time controls
	if (ctl === undefined) {
		fst.form.timeselect($('[data-fst="form-control-time"]'));
		return;
	}

	// Convert each FST time control
	jQuery(ctl).filter('[data-fst="form-control-time"]').each(function () {

		var sel = jQuery('<select></select>');
		var time = jQuery(this);

		sel.attr('id', time.attr('id'));
		sel.attr('name', time.attr('name'));
		sel.data('fst', 'form-control-timeselect');

		var min = time.attr('min') ? time.attr('min') : '00:00';
		var max = time.attr('max') ? time.attr('max') : '23:59';

		var step = time.attr('step') ? time.attr('step') : 300;

		var val = time.val();

		var tm = new Date('01/01/2001 ' + min);
		var tm_end = new Date('01/01/2001 ' + max);

		while (tm <= tm_end) {

			var ts = tm.toTimeString().substring(0, 5);

			var hr = tm.getHours();
			var mn = tm.getMinutes();
			var ap = hr < 12 ? 'am' : 'pm';
			if (hr === 0) hr = 12;
			if (hr > 12) hr -= 12;
			if (mn < 10) mn = '0' + mn;
			var ts2 = hr + ':' + mn + '&nbsp;' + ap;

			sel.append(val == ts ?
				('<option value="' + ts + '" selected="selected">' +
					ts2 + '</option>') :
				('<option value="' + ts + '">' + ts2 + '</option>'));

			tm = new Date(tm.getTime() + step * 1000);
		}

		if (val && !sel.find('[selected]').length) {
			tm = new Date('01/01/2001 ' + val);

			var ts = tm.toTimeString().substring(0, 5);

			var hr = tm.getHours();
			var mn = tm.getMinutes();
			var ap = hr < 12 ? 'am' : 'pm';
			if (hr === 0) hr = 12;
			if (hr > 12) hr -= 12;
			if (mn < 10) mn = '0' + mn;
			var ts2 = hr + ':' + mn + '&nbsp;' + ap;

			sel.prepend('<option value="' + ts + '" selected="selected">' +
				ts2 + '</option>');
		}

		sel.prepend(val == '' ?
			'<option value="" selected="selected">--:-- --</option>' :
			'<option value="">--:-- --</option>');

		time.replaceWith(sel);
	});
}

/**
 * @brief Convert relative URI to absolute URI.
 * @fn String fst.uri (String uri);
 * @param uri URI string (absolute or relative)
 * @return An absolute URI string
 *
 * Converts relative URI strings to an absolute URI. Relative URI strings
 * given to this function are assumed to be relative to the application's
 * root, in which case the correct absolute URI is returned. If an absolute
 * URI is given, the URI is returned unmodified.
 */
fst.uri = function (uri) {
	var absuri = /^(\w+:|\/|\?)/;
	return absuri.test(uri) ? uri : (_approot ? _approot : '/') + uri;
}

// Convert to mm/dd/yyyy date format, if in yyyy-mm-dd format
fst.dt_mdy = function (dt) {
	var re = /^(\d{4})-(\d\d)-(\d\d)$/;
	return dt.match(re) ?
		dt.replace(/^(\d{4})-(\d\d)-(\d\d)$/, '$2/$3/$1') : dt;
}

// Set up active hyperlinks. This sets up all a tags with href beginning
//	with '?' to initiate an Ajax request, or invoke the defined action
//	function (if any).
jQuery(document).on('click', 'a[href^="?"]', null, function (event) {

	// Get action string, follows '?' and ends with non-word character
	var action = jQuery(this).attr('href').substring(1).replace(/\W.*$/, '');

	// If action defined and is false, allow default processing to proceed.
	if (fst.action[action] !== false) {
		// Prevent default processing.
		event.preventDefault();
		fst.action[action] ?
			// Action is defined (assumed to be a function).
			fst.action[action].apply(jQuery(this)) :
			// Action not defined, initiate an Ajax call.
			fst.ajax(jQuery(this).attr('href').substring(1),
				{ data: jQuery(this).data() });
	}
});

// Set up button actions. This sets up all input buttons with the
//	data-fst-href attribute to initiate an Ajax request, or invoke the
//	defined action function (if any).
jQuery(document).on('click',
		'input[type="button"][data-fst-href], button[data-fst-href]',
		null, function (event) {

	// Get DATA-FST-HREF, to simulate A:HREF behavior
	var href = jQuery(this).attr('data-fst-href');

	// Test HREF to determine behavior
	if (href.match(/^\?/)) {
		// HREF starts with '?', process FST action
		var action = href.substring(1).replace(/\W.*$/, '');
		if (fst.action[action] !== false) {
			fst.action[action] ?
				fst.action[action].apply(jQuery(this)) :
				fst.ajax(href.substring(1), { data: jQuery(this).data() });
		}
	}
	else
		// HREF is a URI, redirect
		window.location = href;
});

// Set up Ajax forms.
jQuery(document).on('submit',
		'form[data-fst="form"][action^="?_form="]', null, function (event) {

	event.preventDefault();

	// Get form and form name.
	var form = jQuery(this);
	var name = fst.form.name(form);

	// Set up options. Options may be set via fst.form function.
	options = jQuery.extend({
			callback: function (response) { },
			callback_fail: function (response)
				{ fst.form.errors(this, response.errors); },
			//data: jQuery(form).serialize(),
			data: fst.form.data(form),
			preprocess: function (options) { },
			postprocess: function () { }
		},
		fst.form._options[name] ? fst.form._options[name] : new Object());

	// Clear form errors.
	fst.form.errors.clear(form);

	// Call preprocessor function (if returns false, quit)
	if (options.preprocess.apply(form, [ options ]) === false) return;

	// Prepare ajax options
	var ajax_options = { url: jQuery(form).attr('action'), type: 'POST' };
	var file_controls =
		jQuery(form).find('input[data-fst|="form-control-file"]');
	if (file_controls.length) {
		ajax_options.data = new FormData();
		ajax_options.processData = false;
		ajax_options.contentType = false;
		jQuery.each(options.data,
			function (key, value) { ajax_options.data.append(key, value); });
		file_controls.each(function () {
			var files = jQuery(this).prop('files');
			var name = jQuery(this).attr('name');
			for (var i = 0; i < files.length; i++)
				ajax_options.data.append(name, files[i], files[i].name);
		});
		if (options.progress)
			ajax_options.xhr = function () {
				var xhr = new window.XMLHttpRequest();
				xhr.upload.addEventListener('progress', function (event) {
					if (event.lengthComputable)
						options.progress(
							Math.round(100 * event.loaded / event.total),
							event.loaded, event.total);
					else
						options.progress(false, 0, 0);
				});
				return xhr;
			}
	}
	else
		ajax_options.data = options.data;


	// Submit form via Ajax
	jQuery.ajax(ajax_options).done(function (response) {
		response.valid ?
			options.callback.apply(form, [ response ]) :
			options.callback_fail.apply(form, [ response ]);
		options.postprocess.apply(form);
	});
});

// Set up response for cancel button on fst forms. On click, check to see
//	if form has a 'cancel' function. If so, execute it, if not, redirect
//	to the previous page. If the button is inside a dialog (managed by
//	fst-jqueryui), do nothing as fst-jqueryui takes its own action for
//	such forms.
jQuery(document).on('click',
		'form[data-fst="form"] button[data-fst="form-cancel"]',
			null, function (event) {
	var frm = jQuery(this).closest('form');
	var name = fst.form.name(frm);
	var cancel = fst.form._options[name] && fst.form._options[name].cancel ?
		fst.form._options[name].cancel : fst.form.cancel;
	cancel.apply(frm);
});

// Perform initialization of selected form controls.
jQuery(document).ready(function () {

	// If legacy option for datepicker is used, determine if browser has
	//	native support for date controls.
	if (fst._init.datepicker == 'legacy') {
		var tmp;
		tmp = document.createElement('input');
		tmp.setAttribute('type', 'date');
		fst._init.datepicker = tmp.type != 'date';
	}

	// If legacy option for timeselect is used, determine if browser has
	//	native support for time controls.
	if (fst._init.timeselect == 'legacy') {
		var tmp;
		tmp = document.createElement('input');
		tmp.setAttribute('type', 'time');
		fst._init.timeselect = tmp.type != 'time';
	}

	// Convert controls, if needed.
	if (fst._init.datepicker) fst.form.datepicker();
	if (fst._init.timeselect) fst.form.timeselect();
});
