all : fst-jquery.min.js fst-jqueryui.min.js
	continue

fst-jquery.min.js : fst-jquery.js
	uglifyjs fst-jquery.js > fst-jquery.min.js

fst-jqueryui.min.js : fst-jqueryui.js
	uglifyjs fst-jqueryui.js > fst-jqueryui.min.js
